server:
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forestory-local-database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: forestory-local-user
    password: forestory-local-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_OPTION:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password:
      repositories:
        enabled: false

logging:
  level:
    root: info
