spring:
  application:
    name: forestory-be

  config:
    import: optional:classpath:.env[.properties]

  profiles:
    active: ${PROFILE:local}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: sooptory

