version: '3'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql8-local
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: forestory-local-user
      MYSQL_PASSWORD: forestory-local-password
      MYSQL_DATABASE: forestory-local-database
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    volumes:
      - forestory-local-database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.2.4-alpine
    container_name: redis7-local
    command: redis-server --port 6379
    restart: always
    hostname: root
    labels:
      - 'mode:standalone'
    ports:
      - '6380:6379'

volumes:
  forestory-local-database: