name: Deploy DEV

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup deploy environment
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.SPRING_ENV }}" > ./src/main/resources/.env

      - name: Caching gradle
        uses: actions/cache@v3
        id: cache-gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build gradle
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      - name: Setup docker build tools
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ secrets.IMAGE_TAG }}

  docker-pull-and-restart:
    runs-on: [ self-hosted, Linux, X64, dev ]
    needs: docker-build-and-push
    if: success()

    steps:
      - name: Pull docker image
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker pull ${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ secrets.IMAGE_TAG }}

      - name: Run deploy script
        working-directory: /home/ubuntu/dev
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
