name: PR CI Test

on:
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set test environment
        run: |
          docker-compose -f ./docker/docker-compose.yml up -d
          echo "Waiting for services to be ready..."
          for i in {1..30}; do
            docker exec mysql8-local bash -c "mysqladmin ping -h localhost --silent" && \
            docker exec redis7-local redis-cli ping | grep PONG && \
            echo "✅ Services ready." && exit 0
            echo "⏳ Waiting... ($i)"
            sleep 2
          done
          echo "❌ Services did not become ready in time."
          docker-compose -f ./docker/docker-compose.yml logs
          exit 1

      - name: Set environment variables if not exists
        run: |
          if [ -n "${{ secrets.SPRING_ENV }}" ]; then
            echo "${{ secrets.SPRING_ENV }}" | base64 -d > .env
          else
            echo "SPRING_ENV is empty. Skipping .env creation."
          fi

      - name: Run tests
        run: ./gradlew test

      - name: Publish test results to PR
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/test/**/*.xml'
